###Get one article data
GET https://openlongevity.tk/api/articles/{{item}}
Accept: application/json

###Get articles list
GET http://openlongevity.tk/api/articles
Accept: application/json

###Get articles list with pagination
GET http://openlongevity.tk/api/articles?page=1
Accept: application/json

###Get articles list filtered from the newest
GET http://openlongevity.tk/api/articles?page=1&sort=new
Accept: application/json
