name: Download the latest translations

jobs:
  localazy-download:
    if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main' }}
    name: Download translations from Localazy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: localazy/download@v1
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit latest translations from Localazy.